platform :ios, '8.0'

target 'YanXiuStudentApp-iPhone' do

pod 'CocoaLumberjack', '~> 2.0'
pod 'ReactiveCocoa', :git => 'https://github.com/zhao0/ReactiveCocoa.git', :tag => '2.5.2'
pod 'MagicalRecord', '~> 2.0'
pod 'ASIHTTPRequest', '1.8.2'
pod 'JSONModel'
pod 'Masonry', '~> 0.0'
#pod 'SDWebImage', '~> 3.0'
pod 'pop', '~> 1.0'
pod 'Aspects', '~> 1.4'
pod 'PhotoTweaks', '~> 1.0.3'

pod 'OpenUDID', '1.0.0'
pod 'UIColor-Utilities', '1.0.1'
pod 'NSString-Hashes', '1.2.1'
pod 'MSDynamicsDrawerViewController', '1.5.1'
pod 'StyledPageControl', '1.0'
pod 'UITableView+FDTemplateLayoutCell', '1.4'
pod 'MBProgressHUD', '0.9'
pod 'AJNotificationView', '0.7'
pod 'SAMTextView', '0.2.2'
pod 'UIDevice+HardwareName', '6.0.0'
pod 'NSData+MD5Digest', '1.0.0'
pod 'FileMD5Hash', '2.0.0'
pod 'MDRadialProgress', '1.3.1'
pod 'RMDateSelectionViewController', '1.3.0'
pod 'RATreeView', '1.0.2'
pod 'IBActionSheet', '0.0.2'
pod 'DTCoreText', '1.6.16'
pod 'MWPhotoBrowser','2.1.1'
#pod 'JSPatch'
pod 'FLAnimatedImage', '~> 1.0'
pod 'uiview-frame-helpers', '~> 0.1.1'

pod 'Base64'
pod 'CommonCrypto'
pod 'FCUUID'
#pod 'Reveal-iOS-SDK', :configurations => ['Debug']
inhibit_all_warnings!

end


